name = "BOPTestAPI"
uuid = "4c862b9d-90c3-47b4-a9d1-cc1c4398311d"
authors = ["Bertrand Kerres"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
